version: 1.0.{build}
pull_requests:  
  do_not_increment_build_number: true
branches:  
  only:
  - master
nuget:  
  disable_publish_on_pr: true    
build_script:
- cmd: .\Build\build.cmd AppVeyor
test: off
artifacts:
- path: Artifacts\NuGet\*
  name: NuGet
install:
- cmd: git submodule update --init --recursive